# -*- coding: utf-8 -*-
"""text_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohN5-kvhqssU6ZgTewNoUT-EOEEkGqRQ

Converts all text to lowercase

Removes extra whitespace

Removes special characters (except common punctuation like . , ! %)

Normalizes unicode (handles accented letters, broken symbols)

Removes stop words

Returns cleaned, space-separated words
"""

!pip install -q spacy
!python -m spacy download en_core_web_sm

import re
import unicodedata
import spacy
import os
from google.colab import files
from pathlib import Path



# 📥 Load spaCy English stopwords
nlp = spacy.load("en_core_web_sm")
STOP_WORDS = nlp.Defaults.stop_words

# 🧹 Define the cleaning function
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r"[^a-zA-Z0-9,.!?$€%-]", " ", text)
    text = unicodedata.normalize("NFKD", text)
    text = re.sub(r'\s+', ' ', text).strip()
    words = text.split()
    words = [word for word in words if word not in STOP_WORDS]
    return " ".join(words)

# 📁 Ensure output directory exists
cleaned_dir = "DATA/cleaned_texts"
os.makedirs(cleaned_dir, exist_ok=True)

# 📤 Upload file via Colab file picker
uploaded = files.upload()  # User uploads a .txt file

# 🔄 Clean and save each uploaded file
for filename in uploaded.keys():
    try:
        with open(filename, "r", encoding="utf-8") as f:
            raw_text = f.read()
    except UnicodeDecodeError:
        with open(filename, "r", encoding="ISO-8859-1") as f:
            raw_text = f.read()

    # Clean the text
    cleaned = clean_text(raw_text)

    # Save to DATA/cleaned_texts/
    output_path = Path(cleaned_dir) / Path(filename).name
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(cleaned)

    print(f"✅ Cleaned and saved as: {output_path}")

import shutil

shutil.make_archive("cleaned_texts", 'zip', "DATA/cleaned_texts")

from google.colab import files

files.download("cleaned_texts.zip")