# -*- coding: utf-8 -*-
"""pdf_text_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwLetzJUpbjhN-W1PqzUMbnTWdN5Gg6J

This will:

Prompt you to upload a .pdf

Detect if it's scanned or digital

Extract and save the text

Offer to download the .txt file
"""

!apt-get install poppler-utils tesseract-ocr
!pip install pymupdf pdf2image pytesseract

import fitz  # PyMuPDF for digital PDFs
import pytesseract  # OCR for scanned PDFs
from pdf2image import convert_from_path  # Convert scanned PDFs to images
from google.colab import files
from PIL import Image
import os

# Upload your PDF
uploaded = files.upload()
pdf_file = list(uploaded.keys())[0]

def extract_text_from_digital_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    text = ""
    for page in doc:
        text += page.get_text("text") + "\n"
    return text.strip()

def extract_text_from_scanned_pdf(pdf_path):
    images = convert_from_path(pdf_path)
    extracted_text = ""
    for image in images:
        extracted_text += pytesseract.image_to_string(image) + "\n"
    return extracted_text.strip()

def extract_text_from_pdf(pdf_path):
    text = extract_text_from_digital_pdf(pdf_path)
    if len(text.strip()) < 50:
        print(f"📄 {pdf_path} seems scanned, using OCR...")
        text = extract_text_from_scanned_pdf(pdf_path)
    else:
        print(f"📄 {pdf_path} is digital, extracting text directly...")
    return text.strip()

# Extract text
extracted_text = extract_text_from_pdf(pdf_file)

# Save to a new file
output_filename = pdf_file.replace(".pdf", "_extracted.txt")
with open(output_filename, "w", encoding="utf-8") as f:
    f.write(extracted_text)

print(f"✅ Extracted text saved to: {output_filename}")

# Optionally download the text file back to your local machine
files.download(output_filename)